### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8081/repo2cloud/v1/test

###
POST http://localhost:8081/repo2cloud/v1/auth/register
Content-Type: application/json

{
  "name": "Suhel Mujawar",
  "email": "suhelmujawar3269@gmail.com",
  "password": "Suhel@3269",
  "role": "ADMIN",
  "credits": null
}

###
POST http://localhost:8081/repo2cloud/
Content-Type: application/json

{
"userId": 1,
"url": "https://github.com/spring-projects/spring-petclinic",
"status": "PENDING"
}

###
GET http://localhost:8081/repo2cloud/v1/auth/login
Content-Type: application/json

{
  "email": "suhelmujawar3269@gmail.com",
  "password": "Suhel@3269Y"
}


